# Generated by Django 4.2.4 on 2023-08-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("interfaz", "0002_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8)),
                ("first_name", models.CharField(default=None, max_length=50)),
                ("last_name", models.CharField(default=None, max_length=50)),
                ("phone", models.CharField(default=None, max_length=50)),
                ("address", models.CharField(default=None, max_length=50)),
                ("company", models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default=None, max_length=50)),
                ("last_name", models.CharField(default=None, max_length=50)),
                ("address", models.CharField(default=None, max_length=50)),
                ("company", models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(default=None, max_length=100)),
                ("date", models.DateTimeField()),
                (
                    "client",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interfaz.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(default=None, max_length=100)),
                ("stock", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interfaz.provider",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="interfaz.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="sale",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="interfaz.sale",
            ),
        ),
    ]
